version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container-jpa-to-senior-java
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: jpa_to_senior_java
      MYSQL_USER: duynv
      MYSQL_PASSWORD: 123456789
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
volumes:
  mysql-data: